apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend
  labels:
    app: taskflow-backend
spec:
  type: NodePort
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    app: taskflow-backend
